### ISSUE TITLE
Unable to unzip seurat objects

### ISSUE THREAD

**Issue by Eomesodermin** [aulezko/HumanILC1#1]
I tried to access this repo to have a quick look at the dataset but firstly I was unable to clone the repo because it appears your GitHub doesnt have enough data quota for holding this LFS objects. 

I therefore downloaded the repo but have been unsuccessful at unzipping the objects.

gunzip AllTissues_Fig5a_b_c.rds.gz 
gives the following error 
"not in gzip format" 

Inspecting the objects they dont appear to be zipped. I tried to just remove the .gz tag but am unable to read the RDS object in R. Get the error "unknown input format" 

I suspect something occurred when zipping these files and this may need to be redone and reuploaded.

**Comment by aulezko** [comment]
Thank you for noting that. The Seurat objects are now uploaded to Zenodo: https://zenodo.org/records/12785955. Please let me know if any further issues develop. 

Best,
Alina
